### ISSUE TITLE
【已解决】请问运行cd /media/pdlearning && python3 -u pandalearning.py 之后，提示错误

### ISSUE THREAD

**Issue by nnssz** [lostinfever/docker-ubuntu-pandalearning#10]
在N1小钢炮docker中按照教程，建立macnet，运行镜像容器顺利，但是运行python脚本后提示错误，如下：
root@b69355fb60ec:/# cd /media/pdlearning && python3 -u pandalearning.py
Traceback (most recent call last):
  File "pandalearning.py", line 179, in <module>
    dd_status, uname = user.get_user()
  File "/media/pdlearning/pdlearn/user.py", line 10, in get_user
    uname = input("\u8f93\u5165\u7528\u6237\u6807\u8bb0\u540d\uff1a")
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-7: ordinal not in range(128)
Exception in thread \u83b7\u53d6\u66f4\u65b0\u4fe1\u606f...:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/media/pdlearning/pdlearn/threads.py", line 17, in run
    print("\u5f00\u542f\uff1a " + self.name)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

**Comment by nnssz** [comment]
google了一下，是容器内的ubuntu没有默认开启utf-8编码所致：终端输入：
export PYTHONIOENCODING=utf-8
 即可解决这个问题。

但是紧接着出现第二个错误：
root@b69355fb60ec:/media/pdlearning# python3 -u pandalearning.py
开启： 获取更新信息...
输入用户标记名：
正在联网获取更新信息...
版本信息网络错误

是否保存钉钉帐户密码，保存后可后免登陆学习(Y/N)
========================================================================================================================
Mydriver初始化失败
========================================================================================================================
Traceback (most recent call last):
  File "pandalearning.py", line 180, in <module>
    cookies, a_log, v_log = user_flag(dd_status, uname)
  File "pandalearning.py", line 18, in user_flag
    driver_login = mydriver.Mydriver(nohead=False)
  File "/media/pdlearning/pdlearn/mydriver.py", line 47, in __init__
    self.driver = self.webdriver.Chrome(chrome_options=self.options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
